name: Deploy to EC2 with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 도커 이미지 빌드 및 도커 허브 로그인/푸시
      - name: Build & Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/worldcup-app .
          docker push ${{ secrets.DOCKER_USERNAME }}/worldcup-app

      # EC2에 접속하여 배포 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.KEY }}
          script: |
            # 기존 컨테이너 중단 및 삭제 (없으면 패스)
            docker stop worldcup-server || true
            docker rm worldcup-server || true
            
            # 최신 이미지 풀
            docker pull ${{ secrets.DOCKER_USERNAME }}/worldcup-app
            
            # 새 컨테이너 실행 (환경변수 주입)
            docker run -d --name worldcup-server -p 8080:8080 \
              -e AWS_DATASOURCE_URI="${{ secrets.AWS_DATASOURCE_URI }}" \
              -e AWS_DATASOURCE_USERNAME=${{ secrets.AWS_DATASOURCE_USERNAME }} \
              -e AWS_DATASOURCE_PASSWORD=${{ secrets.AWS_DATASOURCE_PASSWORD }} \
              -e AWS_DATASOURCE_CLASSNAME=com.mysql.cj.jdbc.Driver \
              -e AWS_DATASOURCE_PLATFORM=org.hibernate.dialect.MySQLDialect \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e AWS_REGION=${{ secrets.AWS_REGION }} \
              -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
              ${{ secrets.DOCKER_USERNAME }}/worldcup-app
            
            # 미사용 이미지 정리
            docker image prune -f